apiVersion: v1
kind: Pod
metadata:
  name: io-benchmark-pod
  labels:
    app: io-benchmark
    owner: rotemshavitt
spec:
  containers:
  - name: python-benchmarking
    image: pytorch/pytorch:latest 
    command:
    - "/bin/bash"
    - "-c"
    - |
      apt-get update && \
      apt-get install -y build-essential && \
      pip install ninja aiofiles && \
      sleep infinity
    resources:
      requests:
        memory: "100Gi"
        cpu: "12"
      limits:
        memory: "200Gi"
        cpu: "128"
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: "100Gi" # Adjust based on 'buffer_size' variable